name = "cloudfinger"
main = "./src/index.ts"
compatibility_date = "2023-03-14"

kv_namespaces = [
	{ binding = "WEBFINGER", id = "bad0832c31cd425dbeee526eed30be53", preview_id = "be07834ab33648cabf7e19a51804d103" }
]

[vars]
CF_API_ENDPOINT = "https://api.cloudflare.com/client/v4"
